[package]
name = "claimlands-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
ron.workspace = true
thiserror.workspace = true
blake3.workspace = true
libm.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
proptest.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true

[lints]
workspace = true
